### PR TITLE
master < Mh/v1

### PR DESCRIPTION
**Pull request by matthewhively**
As per the notification last year, v0 will be deprecated. This should now use v1.

I compared the JSON schemas, and I don't see any breaking changes between the beta and release versions. Everything appears to be more permissive.

Screen Shot 2020-08-04 at 3 32 10 PM

Once this is done, hopefully we can get this merged into the mainline localytics-ruby branch and we won't need to maintain our own version.

### CODE REVIEW

**Comment by andrewzenk** [comment]
@matthewhively, what is this for? We no longer use Localytics (as of last week).

**Comment by matthewhively** [comment]
@andrewzenk Ok... I guess we don't need it anymore then.
Should probably remove it from the gemfile then.

**Comment by andrewzenk** [comment]
> @andrewzenk Ok... I guess we don't need it anymore then.
> Should probably remove it from the gemfile then.

Hot off the press! Yeah, I've got some "cleanup" branches running to remove references to Localytics (and Campaigner)...

**Comment by sidcpatel** [comment]
Thanks @matthewhively for getting this changes to localytics root repo

https://github.com/tobuy/localytics-ruby/pull/16

We won't use localytics going forward, but out changes will be used by others.

**Pull request merged**
